import './App.css'
import SecondNav from './components/SecondNav'
import TopNav from './components/TopNav'


function App() {
  return (
    <div className="App">

      <TopNav />
      <main className='absolute top-20'>
        <SecondNav />
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam pariatur perferendis similique quo nesciunt accusamus maiores, nobis voluptatibus officiis numquam maxime delectus dolor, ab at voluptate labore. Aperiam illo accusamus harum, nemo repellendus tempore soluta vero beatae, nihil minima, suscipit quidem laboriosam nam. Quae, iusto accusamus omnis voluptates beatae iure explicabo eius perferendis iste qui doloremque temporibus commodi impedit, veniam fugit quaerat nesciunt eveniet. Neque, ea minus. A, numquam at eius voluptas neque explicabo eveniet dicta iste perspiciatis id quod consequuntur, nulla provident? Nihil quis itaque a, aut soluta non ipsam. Excepturi eligendi sit quod voluptas molestiae perferendis pariatur, consectetur quae nemo, maiores voluptates nobis nesciunt officiis doloremque natus sint dolorum quibusdam beatae itaque eos autem qui, possimus nam vero? Architecto quibusdam voluptate at est, dolores repellat quos dolorem maxime totam praesentium dolor vel sapiente voluptas maiores quas, possimus excepturi. Alias eos maiores quisquam error explicabo dolores animi modi possimus soluta nulla recusandae laudantium suscipit, molestiae, fugit iusto delectus vero harum, nostrum cupiditate? Sint ea quo quaerat, est aspernatur possimus quas voluptate eius quae nam veritatis debitis. Rem voluptates rerum perspiciatis distinctio quisquam, explicabo exercitationem beatae laboriosam voluptatibus, incidunt atque expedita, ipsam quos velit dolorum culpa? Corrupti facere adipisci beatae deserunt. Nihil doloribus perferendis qui ducimus quidem laudantium maiores, a aliquid nobis inventore consectetur unde iure magnam, laborum assumenda alias deleniti odio ipsa est sunt, illum placeat ab eligendi pariatur. Magnam expedita similique voluptates quis ullam labore necessitatibus cum impedit nobis velit. Nesciunt, mollitia? Qui alias, veniam vitae voluptates eos itaque asperiores architecto odit adipisci commodi enim culpa, distinctio magnam soluta! In, eum omnis. Suscipit voluptate eaque illum quis accusamus voluptatum tempore, facilis, nisi doloribus nesciunt placeat molestiae hic at eum, illo omnis labore adipisci fuga dolorem distinctio architecto explicabo ratione! Accusantium explicabo praesentium vitae maiores quae natus minus tenetur.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam pariatur perferendis similique quo nesciunt accusamus maiores, nobis voluptatibus officiis numquam maxime delectus dolor, ab at voluptate labore. Aperiam illo accusamus harum, nemo repellendus tempore soluta vero beatae, nihil minima, suscipit quidem laboriosam nam. Quae, iusto accusamus omnis voluptates beatae iure explicabo eius perferendis iste qui doloremque temporibus commodi impedit, veniam fugit quaerat nesciunt eveniet. Neque, ea minus. A, numquam at eius voluptas neque explicabo eveniet dicta iste perspiciatis id quod consequuntur, nulla provident? Nihil quis itaque a, aut soluta non ipsam. Excepturi eligendi sit quod voluptas molestiae perferendis pariatur, consectetur quae nemo, maiores voluptates nobis nesciunt officiis doloremque natus sint dolorum quibusdam beatae itaque eos autem qui, possimus nam vero? Architecto quibusdam voluptate at est, dolores repellat quos dolorem maxime totam praesentium dolor vel sapiente voluptas maiores quas, possimus excepturi. Alias eos maiores quisquam error explicabo dolores animi modi possimus soluta nulla recusandae laudantium suscipit, molestiae, fugit iusto delectus vero harum, nostrum cupiditate? Sint ea quo quaerat, est aspernatur possimus quas voluptate eius quae nam veritatis debitis. Rem voluptates rerum perspiciatis distinctio quisquam, explicabo exercitationem beatae laboriosam voluptatibus, incidunt atque expedita, ipsam quos velit dolorum culpa? Corrupti facere adipisci beatae deserunt. Nihil doloribus perferendis qui ducimus quidem laudantium maiores, a aliquid nobis inventore consectetur unde iure magnam, laborum assumenda alias deleniti odio ipsa est sunt, illum placeat ab eligendi pariatur. Magnam expedita similique voluptates quis ullam labore necessitatibus cum impedit nobis velit. Nesciunt, mollitia? Qui alias, veniam vitae voluptates eos itaque asperiores architecto odit adipisci commodi enim culpa, distinctio magnam soluta! In, eum omnis. Suscipit voluptate eaque illum quis accusamus voluptatum tempore, facilis, nisi doloribus nesciunt placeat molestiae hic at eum, illo omnis labore adipisci fuga dolorem distinctio architecto explicabo ratione! Accusantium explicabo praesentium vitae maiores quae natus minus tenetur.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam pariatur perferendis similique quo nesciunt accusamus maiores, nobis voluptatibus officiis numquam maxime delectus dolor, ab at voluptate labore. Aperiam illo accusamus harum, nemo repellendus tempore soluta vero beatae, nihil minima, suscipit quidem laboriosam nam. Quae, iusto accusamus omnis voluptates beatae iure explicabo eius perferendis iste qui doloremque temporibus commodi impedit, veniam fugit quaerat nesciunt eveniet. Neque, ea minus. A, numquam at eius voluptas neque explicabo eveniet dicta iste perspiciatis id quod consequuntur, nulla provident? Nihil quis itaque a, aut soluta non ipsam. Excepturi eligendi sit quod voluptas molestiae perferendis pariatur, consectetur quae nemo, maiores voluptates nobis nesciunt officiis doloremque natus sint dolorum quibusdam beatae itaque eos autem qui, possimus nam vero? Architecto quibusdam voluptate at est, dolores repellat quos dolorem maxime totam praesentium dolor vel sapiente voluptas maiores quas, possimus excepturi. Alias eos maiores quisquam error explicabo dolores animi modi possimus soluta nulla recusandae laudantium suscipit, molestiae, fugit iusto delectus vero harum, nostrum cupiditate? Sint ea quo quaerat, est aspernatur possimus quas voluptate eius quae nam veritatis debitis. Rem voluptates rerum perspiciatis distinctio quisquam, explicabo exercitationem beatae laboriosam voluptatibus, incidunt atque expedita, ipsam quos velit dolorum culpa? Corrupti facere adipisci beatae deserunt. Nihil doloribus perferendis qui ducimus quidem laudantium maiores, a aliquid nobis inventore consectetur unde iure magnam, laborum assumenda alias deleniti odio ipsa est sunt, illum placeat ab eligendi pariatur. Magnam expedita similique voluptates quis ullam labore necessitatibus cum impedit nobis velit. Nesciunt, mollitia? Qui alias, veniam vitae voluptates eos itaque asperiores architecto odit adipisci commodi enim culpa, distinctio magnam soluta! In, eum omnis. Suscipit voluptate eaque illum quis accusamus voluptatum tempore, facilis, nisi doloribus nesciunt placeat molestiae hic at eum, illo omnis labore adipisci fuga dolorem distinctio architecto explicabo ratione! Accusantium explicabo praesentium vitae maiores quae natus minus tenetur.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam pariatur perferendis similique quo nesciunt accusamus maiores, nobis voluptatibus officiis numquam maxime delectus dolor, ab at voluptate labore. Aperiam illo accusamus harum, nemo repellendus tempore soluta vero beatae, nihil minima, suscipit quidem laboriosam nam. Quae, iusto accusamus omnis voluptates beatae iure explicabo eius perferendis iste qui doloremque temporibus commodi impedit, veniam fugit quaerat nesciunt eveniet. Neque, ea minus. A, numquam at eius voluptas neque explicabo eveniet dicta iste perspiciatis id quod consequuntur, nulla provident? Nihil quis itaque a, aut soluta non ipsam. Excepturi eligendi sit quod voluptas molestiae perferendis pariatur, consectetur quae nemo, maiores voluptates nobis nesciunt officiis doloremque natus sint dolorum quibusdam beatae itaque eos autem qui, possimus nam vero? Architecto quibusdam voluptate at est, dolores repellat quos dolorem maxime totam praesentium dolor vel sapiente voluptas maiores quas, possimus excepturi. Alias eos maiores quisquam error explicabo dolores animi modi possimus soluta nulla recusandae laudantium suscipit, molestiae, fugit iusto delectus vero harum, nostrum cupiditate? Sint ea quo quaerat, est aspernatur possimus quas voluptate eius quae nam veritatis debitis. Rem voluptates rerum perspiciatis distinctio quisquam, explicabo exercitationem beatae laboriosam voluptatibus, incidunt atque expedita, ipsam quos velit dolorum culpa? Corrupti facere adipisci beatae deserunt. Nihil doloribus perferendis qui ducimus quidem laudantium maiores, a aliquid nobis inventore consectetur unde iure magnam, laborum assumenda alias deleniti odio ipsa est sunt, illum placeat ab eligendi pariatur. Magnam expedita similique voluptates quis ullam labore necessitatibus cum impedit nobis velit. Nesciunt, mollitia? Qui alias, veniam vitae voluptates eos itaque asperiores architecto odit adipisci commodi enim culpa, distinctio magnam soluta! In, eum omnis. Suscipit voluptate eaque illum quis accusamus voluptatum tempore, facilis, nisi doloribus nesciunt placeat molestiae hic at eum, illo omnis labore adipisci fuga dolorem distinctio architecto explicabo ratione! Accusantium explicabo praesentium vitae maiores quae natus minus tenetur.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam pariatur perferendis similique quo nesciunt accusamus maiores, nobis voluptatibus officiis numquam maxime delectus dolor, ab at voluptate labore. Aperiam illo accusamus harum, nemo repellendus tempore soluta vero beatae, nihil minima, suscipit quidem laboriosam nam. Quae, iusto accusamus omnis voluptates beatae iure explicabo eius perferendis iste qui doloremque temporibus commodi impedit, veniam fugit quaerat nesciunt eveniet. Neque, ea minus. A, numquam at eius voluptas neque explicabo eveniet dicta iste perspiciatis id quod consequuntur, nulla provident? Nihil quis itaque a, aut soluta non ipsam. Excepturi eligendi sit quod voluptas molestiae perferendis pariatur, consectetur quae nemo, maiores voluptates nobis nesciunt officiis doloremque natus sint dolorum quibusdam beatae itaque eos autem qui, possimus nam vero? Architecto quibusdam voluptate at est, dolores repellat quos dolorem maxime totam praesentium dolor vel sapiente voluptas maiores quas, possimus excepturi. Alias eos maiores quisquam error explicabo dolores animi modi possimus soluta nulla recusandae laudantium suscipit, molestiae, fugit iusto delectus vero harum, nostrum cupiditate? Sint ea quo quaerat, est aspernatur possimus quas voluptate eius quae nam veritatis debitis. Rem voluptates rerum perspiciatis distinctio quisquam, explicabo exercitationem beatae laboriosam voluptatibus, incidunt atque expedita, ipsam quos velit dolorum culpa? Corrupti facere adipisci beatae deserunt. Nihil doloribus perferendis qui ducimus quidem laudantium maiores, a aliquid nobis inventore consectetur unde iure magnam, laborum assumenda alias deleniti odio ipsa est sunt, illum placeat ab eligendi pariatur. Magnam expedita similique voluptates quis ullam labore necessitatibus cum impedit nobis velit. Nesciunt, mollitia? Qui alias, veniam vitae voluptates eos itaque asperiores architecto odit adipisci commodi enim culpa, distinctio magnam soluta! In, eum omnis. Suscipit voluptate eaque illum quis accusamus voluptatum tempore, facilis, nisi doloribus nesciunt placeat molestiae hic at eum, illo omnis labore adipisci fuga dolorem distinctio architecto explicabo ratione! Accusantium explicabo praesentium vitae maiores quae natus minus tenetur.
        </p>
      </main>

    </div>
  )
}

export default App
